// ============================================================================
// Novalistically — Zod Schemas for YAML File Validation (barrel)
// Every exported schema uses .strict() to reject unknown fields.
// ============================================================================

// ── Import all per-entity schemas ────────────────────────────────────────────

import { chapterMetadataSchema } from './chapter.js';
import { characterDefinitionSchema } from './character.js';
import {
  anachronyFunctionSchema,
  anachronySchema,
  anachronyScopeSchema,
  anachronyTypeSchema,
  diegeticRelationSchema,
  narrativeLevelSchema,
  voiceProfileSchema,
} from './discourse.js';
import { durationProfileSchema, durationTypeSchema } from './duration.js';
import {
  attributeDefinitionSchema,
  attributeDefinitionSourceSchema,
  attributeValueTypeSchema,
  entityDeclarationCatalogSchema,
  entityDeclarationSchema,
  entityIntroductionSchema,
  entityRuntimeStateSchema,
  entityTypeCatalogSchema,
  entityTypeCatalogSourceSchema,
  entityTypeDefinitionSchema,
  entityTypeDefinitionSourceSchema,
  entityTypeRefSchema,
  requiredAtSchema,
  writePolicySchema,
} from './entity-catalog.js';
import { eventFileSchema } from './event.js';
import { factionDefinitionSchema } from './faction.js';
import { frequencyProfileSchema, frequencyTypeSchema } from './frequency.js';
import {
  gameDialogueChoiceSchema,
  gameDialogueChoicesSchema,
  gameDialogueEffectSchema,
} from './game-dialogue.js';
import { greyLineNodeSchema, greyLineSchema } from './grey-line.js';
import {
  emotionalArcDefinitionSchema,
  emotionalBeatSchema,
  ideaIRSchema,
  thematicIntentSchema,
} from './idea-ir.js';
import { itemDefinitionSchema } from './item.js';
import { locationDefinitionSchema } from './location.js';
import {
  checklistResultSchema,
  narrativeChecklistItemSchema,
  narrativeChecklistSchema,
} from './narrative-checklist.js';
import {
  absentApparatusSchema,
  causalDiscontinuitySchema,
  causalMultiplicitySchema,
  irresolvableIndeterminacySchema,
  metanarrativeLevelSchema,
  multiplicitySchema,
  surfaceModeSchema,
  voiceDissonanceSchema,
} from './narrative-techniques.js';
import { projectConfigSchema } from './project.js';
import {
  relationshipDefinitionSchema,
  relationshipTransactionSchema,
  relationshipTypeDefinitionSchema,
} from './relationship.js';
import {
  ruleActivationSchema,
  ruleApplicableEffectivenessSchema,
  ruleClassSchema,
  ruleConstraintKindSchema,
  ruleConstraintSchema,
  ruleDefinitionSchema,
  ruleEffectEntrySchema,
  ruleEffectivenessSchema,
  ruleEnforcementSchema,
  ruleEpochIdSchema,
  ruleEvaluationRecordSchema,
  ruleEvaluationResultSchema,
  ruleExceptionConditionSchema,
  ruleExceptionEffectSchema,
  ruleExceptionIdSchema,
  ruleExceptionSchema,
  ruleIdSchema,
  rulePredicateSchema,
  ruleRuntimeStateSchema,
  ruleSpecificationIdSchema,
  ruleSpecificationSchema,
  ruleTransactionOperationSchema,
  ruleTransactionSchema,
  ruleTypeDefinitionSchema,
} from './rule.js';
import { sourceContextEntrySchema, sourceContextSchema } from './source-context.js';
import { worldInitialStateSchema } from './state-initial.js';
import { actantModelSchema, storyArchetypeSchema, structuralFunctionSchema } from './story-ir.js';

// ── Re-export all per-entity schemas ─────────────────────────────────────────
export {
  analysisAlternativeSchema,
  analysisObservationSchema,
  analysisResultSchema,
  buildAnalysisResultSchema,
} from './analysis.js';
// ——— CORPUS-1: NarrativeEllipsis & NarrativeNode Schemas ———
export {
  ellipsisProvenanceSchema,
  informationActSchema,
  isNarrativeEllipsis,
  isNarrativeEllipsisFile,
  isNarrativeEvent,
  isNarrativeNode,
  narrativeEllipsisFileSchema,
  narrativeEllipsisSchema as corpusNarrativeEllipsisSchema,
  narrativeEventSchema as corpusNarrativeEventSchema,
  narrativeNodeSchema as corpusNarrativeNodeSchema,
} from './corpus.js';
// ——— GRAPH-1: Typed Causal Graph Schemas ———
export {
  discourseCoordinateSchema,
  discourseGraphSchema,
  edgeClassSchema,
  effectiveCoordinateSchema,
  graphAbsenceWitnessSchema,
  graphBoundaryReferenceSchema,
  graphCacheEntrySchema,
  graphEdgeSchema,
  graphNarrativeEllipsisSchema,
  graphProviderOutputSchema,
  graphReadResolutionSchema,
  graphSchema,
  initialStoryCoordinateSchema,
  outputDescriptorSchema,
  outputValueSchema,
  pointStoryCoordinateSchema,
  presencePredicateSchema,
  readOriginSchema,
  readPhaseSchema,
  readRequirementSchema,
  sceneStoryCoordinateSchema,
  storyCoordinateSchema,
  storyGraphSchema,
  unlocatedStoryCoordinateSchema,
} from './graph.js';
// ——— STATE-4 Knowledge/Belief Schemas ———
export {
  actPropositionSchema,
  claimAssessmentSchema,
  claimEvidenceRecordSchema,
  claimGradeSchema,
  claimPolaritySchema,
  claimSchema,
  commonGroundRecordSchema,
  conflictedAssessmentSchema,
  epistemicLedgerSchema,
  epistemicPropositionSchema,
  evaluationResultSchema,
  evidenceSourceSchema,
  forgottenAssessmentSchema,
  groundedPropositionSchema,
  groupEpistemicModeSchema,
  groupEpistemicQueryDefinitionSchema,
  informationActTypeSchema,
  intensionalPropositionSchema,
  narrativeKnowledgeBoundarySchema,
  propositionCatalogSchema,
  propositionSchema,
  settledAssessmentSchema,
  suspendedAssessmentSchema,
  unsetAssessmentSchema,
} from './knowledge.js';
// ——— STATE-5 Thread Schemas ———
export {
  goalLifecycleSchema,
  goalStateSchema,
  milestoneLifecycleSchema,
  milestoneStateSchema,
  threadDeclarationCatalogSchema,
  threadDeclarationSchema,
  threadIdSchema,
  threadLifecycleSchema,
  threadMergeResultSchema,
  threadMergeStrategySchema,
  threadRunIdSchema,
  threadRuntimeStateSchema,
  threadTransactionSchema,
  threadTypeCatalogSchema,
  threadTypeDefinitionSchema,
  timeDomainSchema,
} from './thread.js';
// ——— Shared authored timestamp schemas ———
export {
  absoluteTimestampSchema,
  authoredIndeterminateTimestampSchema,
  authoredLocatableStoryTimeSchema,
  authoredStoryTimeSchema,
  chapterTimestampSchema,
  indeterminateTimestampSchema,
  locatableStoryTimestampSchema,
  relativeTimestampSchema,
  storyOffsetTimestampSchema,
  storyTimestampSchema,
  timeUnitSchema,
} from './timestamp.js';
export {
  absentApparatusSchema,
  actantModelSchema,
  anachronyFunctionSchema,
  anachronySchema,
  anachronyScopeSchema,
  anachronyTypeSchema,
  attributeDefinitionSchema,
  attributeDefinitionSourceSchema,
  attributeValueTypeSchema,
  causalDiscontinuitySchema,
  causalMultiplicitySchema,
  chapterMetadataSchema,
  characterDefinitionSchema,
  checklistResultSchema,
  diegeticRelationSchema,
  durationProfileSchema,
  durationTypeSchema,
  emotionalArcDefinitionSchema,
  emotionalBeatSchema,
  entityDeclarationCatalogSchema,
  entityDeclarationSchema,
  entityIntroductionSchema,
  entityRuntimeStateSchema,
  entityTypeCatalogSchema,
  entityTypeCatalogSourceSchema,
  entityTypeDefinitionSchema,
  entityTypeDefinitionSourceSchema,
  entityTypeRefSchema,
  eventFileSchema,
  factionDefinitionSchema,
  frequencyProfileSchema,
  frequencyTypeSchema,
  gameDialogueChoiceSchema,
  gameDialogueChoicesSchema,
  gameDialogueEffectSchema,
  greyLineNodeSchema,
  greyLineSchema,
  ideaIRSchema,
  irresolvableIndeterminacySchema,
  itemDefinitionSchema,
  locationDefinitionSchema,
  metanarrativeLevelSchema,
  multiplicitySchema,
  narrativeChecklistItemSchema,
  narrativeChecklistSchema,
  narrativeLevelSchema,
  projectConfigSchema,
  relationshipDefinitionSchema,
  relationshipTransactionSchema,
  relationshipTypeDefinitionSchema,
  requiredAtSchema,
  ruleActivationSchema,
  ruleApplicableEffectivenessSchema,
  ruleClassSchema,
  ruleConstraintKindSchema,
  ruleConstraintSchema,
  ruleDefinitionSchema,
  ruleEffectEntrySchema,
  ruleEffectivenessSchema,
  ruleEnforcementSchema,
  ruleEpochIdSchema,
  ruleEvaluationRecordSchema,
  ruleEvaluationResultSchema,
  ruleExceptionConditionSchema,
  ruleExceptionEffectSchema,
  ruleExceptionIdSchema,
  ruleExceptionSchema,
  ruleIdSchema,
  rulePredicateSchema,
  ruleRuntimeStateSchema,
  ruleSpecificationIdSchema,
  ruleSpecificationSchema,
  ruleTransactionOperationSchema,
  ruleTransactionSchema,
  ruleTypeDefinitionSchema,
  sourceContextEntrySchema,
  sourceContextSchema,
  storyArchetypeSchema,
  structuralFunctionSchema,
  surfaceModeSchema,
  thematicIntentSchema,
  voiceDissonanceSchema,
  voiceProfileSchema,
  worldInitialStateSchema,
  writePolicySchema,
};

// These supersede the integration.ts schemas and carry full binding-constraint validation.

// ——— CAPABILITY-1: Capability Manifest schemas ———
export {
  capabilityManifestEntrySchema,
  capabilityManifestEntrySchemaZ,
  capabilityManifestSchema,
  capabilityManifestSchemaZ,
  capabilityStatusSchema,
  capabilityStatusSchemaZ,
  evidenceClassSchema,
  evidenceClassSchemaZ,
  stageGateSchema,
  stageGateSchemaZ,
} from './capability.js';
// ——— DISCOURSE-1: Discourse State & Narrator Schemas ———
export {
  assertionEvidenceSchema,
  assertionPolaritySchema,
  assertionTypeSchema,
  audienceSemanticsSchema,
  claimActionSchema,
  correctionActionSchema,
  disclosureActionSchema,
  disclosureObservationSchema,
  discourseCacheKeySchema,
  discourseContextProjectionSchema,
  discoursePositionActionSchema,
  discoursePositionSchema,
  discourseStateSchema,
  explicitLedgerProfileSchema,
  focalizerBoundProfileSchema,
  hintActionSchema,
  hintSchema,
  hintStateSchema,
  initialExposureContractSchema,
  ledgerChapterSchema,
  modelReaderProfileIdSchema,
  modelReaderProfileSchema,
  narrationBoundarySchema,
  narrationDisclosurePolicySchema,
  narratorAccessSchema,
  narratorAssertionCapabilitySchema,
  narratorAssertionSchema,
  narratorAssertionStatusSchema,
  narratorFidelitySchema,
  narratorProfileBaseSchema,
  narratorProfileSchema,
  narratorProfileTypeSchema,
  narratorSinceritySchema,
  narratorTruthCapabilitySchema,
  omniscientProfileSchema,
  plannedDiscourseLedgerSourceSchema,
  plannedLedgerEntrySchema,
  retractionActionSchema,
  retrospectiveEntityProfileSchema,
  revealActionSchema,
  validationKeySchema,
  withholdEndActionSchema,
  withholdingPolicySchema,
  withholdStartActionSchema,
} from './discourse.js';
// ——— EDITORIAL: Schema exports for the editorial pipeline ———
export {
  branchPathV1Schema,
  branchSetV1Schema,
  editorialErrorSchema,
  editorialMutationContextSchema,
  editorialOperationV1Schema,
  editorialPreviewRequestV1Schema,
  editorialProgressEventV1Schema,
  editorialRenderRequestV1Schema,
  renderGameDialogueTreeRequestV1Schema,
  sceneMetadataV1Schema,
  sceneRevisionEnvelopeV1Schema,
  sceneSelectorSchema,
  sourceChangePreviewV1Schema,
  sourceChangeSetV1Schema,
  sourceDocumentChangeSchema,
} from './editorial.js';
// ——— INTEGRATION-1: Cross-domain resolution, Merge & dual coverage ———
export {
  absenceBasisSchema,
  absenceWitnessSchema,
  boundaryReferenceSchema,
  coverageManifestSchema,
  discourseBridgeSchema,
  discourseNodeSchema,
  discourseSnapshotSchema,
  excerptDisclosureCheckpointSchema,
  fullWorkContextSchema,
  mergePlanProvenanceSchema,
  mergePlanSchema,
  mergePolicySchema,
  narrativeEllipsisSchema,
  narrativeNodeSchema,
  providerOutputSchema,
  readResolutionSchema,
  readResolutionUnionSchema,
  scenePresentationSchema,
  sparseRunDeclarationSchema,
  storySnapshotCatalogHashesSchema,
  storySnapshotSchema,
  storySnapshotTombstonesSchema,
} from './integration.js';
// ——— INTEGRATION-2: ReferenceEligibility & lifecycle closure ———
export {
  referenceEntrySchema,
  referenceIndexSchema,
  referenceKindSchema,
  referenceModeSchema,
} from './reference.js';
// ——— RENDER-SURFACE-1: Surface render, group & cache schemas ———
export {
  attemptKeySchema,
  autoGroupConfigSchema,
  compiledSceneContractSchema,
  continuityPacketSchema,
  excerptModeSchema,
  logicalRenderKeySchema,
  plannerModeSchema,
  renderGroupManifestSchema,
  renderGroupSchema,
  renderSurfaceAutoConfigSchema,
  renderSurfaceConfigSchema,
  renderSurfaceExtractionSchema,
  renderSurfaceGroupSchema,
  renderSurfaceLaneSchema,
  sceneTransitionSchema,
  serialLaneSchema,
  styleMetricsSchema,
  styleProfileSchema,
  styleResolutionPathSchema,
  surfaceDependencyGraphSchema,
  surfaceErrorCodeSchema,
  surfacePlannerOptionsSchema,
  surfacePlanResultSchema,
  surfacePolicySchema,
  surfaceReferencePacketSchema,
  surfaceRenderKeySchema,
  surfaceValidationKeySchema,
  validationGateGraphSchema,
  validationGateSchema,
  validationGateStatusSchema,
  validationPolicySchema,
} from './render-surface.js';
// ——— REVIEW V1: Schema exports for the semantic review ledger ———
export {
  newReviewCommentSchema,
  reviewApplicationV1Schema,
  reviewCommentSchema,
  reviewLedgerV1Schema,
} from './review.js';
