// ============================================================================
// Editorial revision — execution-repository derived revision state
//
// Revision requests must resolve the accepted head/prose, applicable reviews
// and the request instruction BEFORE compilation/job construction, so the
// real provider Pass-1 prompt carries the base prose plus the canonical
// instruction/review material in deterministic order. Missing accepted bases
// block with the canonical NO_ACCEPTED_BASE preflight before any provider
// call. All repository access is CoreExecutionRepository; no filesystem.
// ============================================================================

import * as crypto from 'node:crypto';
import { describe, expect, it } from 'vitest';
import type { MockPass2Entry } from '../../src/ai/providers/mock-pass2.ts';
import { MockPass2Provider } from '../../src/ai/providers/mock-pass2.ts';
import { previewEditorialRun, renderNovel } from '../../src/api.ts';
import type { ProjectSourceSnapshotV1, SourceDocumentV1 } from '../../src/contracts/source.ts';
import { ReviewManager } from '../../src/review/manager.ts';
import {
  MemoryExecutionRepository,
  MemoryRenderCacheRepository,
  MemoryStateLogRepository,
  MemoryStateSnapshotRepository,
} from '../../src/testing/memory-repositories.ts';
import type { EditorialRuntime } from '../../src/types/editorial.ts';
import { makeCustomEntry, makeObservations, makeProtocol } from '../fixtures/mock-pass2-helpers.ts';

const PROJECT_ID = 'test-project';
const hash = (value: string): string => crypto.createHash('sha256').update(value).digest('hex');
const BASE_PROSE = 'The old accepted prose for E1, settled in a prior pass.';
const REVISED_PROSE = 'Revised prose for E1, freshly generated by the revision pass.';
const payload: Record<string, unknown> = {
  postconditions: { covered: [], dropped: [] },
  preconditions: { violated: [] },
  pov: { consistent: true, leaks: [] },
  inventedDetails: [],
  quality: {
    proseScore: 4,
    maxScore: 5,
    strengths: ['clear prose'],
    weaknesses: [],
    estimatedWordCount: 80,
  },
  threadProgressAchieved: [],
  foreshadowingDeployed: [],
  narrativeChecks: [],
  appearanceChecks: [],
  characterReferences: [],
  tenseDetected: 'past',
  ruleChecks: [],
  conflictAnalysis: { primaryType: 'none', resolutionAchieved: true },
  knowledgeChecks: [],
  checklistResults: [],
};

function source(): ProjectSourceSnapshotV1 {
  const entries: Record<string, string> = {
    'nova.yaml': `project: ${PROJECT_ID}\ntitle: Test Novel\nauthor: Test Author\ndefaultModel: mock-pass2\ndefaultLanguage: en\n`,
    'definitions/state_initial.yaml':
      'info:\n  currentEra: contemporary\n  politicalSituation: stable\ntimeAnchors:\n  - { id: day_1, at: day_1, description: Day 1 }\nthreads: []\nworldFacts: []\nknowledge: { claims: [], commonGround: [] }\n',
    'definitions/thread-types.yaml':
      'types:\n  primary:\n    typeId: primary\n    description: Primary narrative thread type\n    allowedPhases: [opening, development, resolution]\n    lifecyclePolicy: { reopenPolicy: forbidden }\n    timeDomain: story\n    stableGoals: []\n    stableMilestones: []\n',
    'definitions/propositions.yaml': 'version: 1\npropositions: {}\ndependencyGraph: {}\n',
    'definitions/relationship-types.yaml': 'types: {}\n',
    'definitions/rule-types.yaml': 'types: {}\n',
    'definitions/characters/narrator.yaml':
      'id: narrator\nname: Narrator\ntype: person\ndescription: The narrator\ninitialState: {}\ntraits: []\n',
    'definitions/entity-types.yaml':
      'types:\n  character:\n    typeId: character\n    kind: character\n    attributes:\n      lifecycle:\n        attributeId: lifecycle\n        valueType: string\n        requiredAt: introduction\n        writePolicy: lifecycle_managed\n        allowedLifecycleStates: [active, inactive, retired]\n        unsetAllowed: false\n        semanticRole: lifecycle\n      traits:\n        attributeId: traits\n        valueType: string_list\n        requiredAt: never\n        writePolicy: immutable\n        unsetAllowed: true\n    lifecyclePolicy:\n      allowedTransitions:\n        - [active, inactive]\n        - [active, retired]\n        - [inactive, active]\n        - [inactive, retired]\n    referenceCapabilities:\n      defaultEligibility: live\n    typedInvariants: []\n',
    'definitions/discourse-ledger.yaml':
      'id: test-ledger\nchapters:\n  - branch: main\n    chapter: 1\n    sceneIds: [E1]\nentries: []\n',
    'chapters/chapter_01/_chapter.yaml':
      'chapter: 1\ntitle: Chapter 1\nsummary: First chapter\nintent: Introduction\nplannedScenes: 1\n',
    'chapters/chapter_01/E1.yaml':
      'event: E1\nnarrativeOrder: 1\ntitle: First Event\nstoryTime: day_1\npov:\n  character: narrator\n  type: first_person\nsceneBrief: A test scene.\nbeats:\n  - A test scene.\npreconditions: []\nexpectedPostconditions: []\n',
  };
  const documents: SourceDocumentV1[] = Object.entries(entries)
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([logicalPath, content]) => ({
      version: 1,
      logicalPath,
      content,
      contentHash: hash(content),
      parseResult: { status: 'parsed', value: { value: content } },
      diagnostics: [],
    }));
  return {
    version: 1,
    documents,
    sourceHash: hash(
      documents.map((document) => `${document.logicalPath}\0${document.content}`).join(''),
    ),
  };
}

function entry(eventId: string, prose: string): MockPass2Entry {
  return makeCustomEntry(eventId, prose, {
    eventId,
    protocol: makeProtocol(prose),
    observations: makeObservations(payload, prose),
    analysis: payload,
  });
}

function services(
  provider: MockPass2Provider,
  promptTemplates: EditorialRuntime['services']['promptTemplates'] = { get: async () => null },
): EditorialRuntime['services'] {
  return {
    execution: new MemoryExecutionRepository(),
    renderCache: new MemoryRenderCacheRepository(),
    stateLog: new MemoryStateLogRepository(),
    stateSnapshots: new MemoryStateSnapshotRepository(),
    promptTemplates,
    clock: { now: () => new Date().toISOString() },
    ids: { next: () => crypto.randomUUID() },
    llm: provider,
  };
}

/** Wrap complete() to count calls and capture every Pass-1 user prompt. */
function capture(provider: MockPass2Provider): { pass1Prompts: string[]; callCount(): number } {
  const pass1Prompts: string[] = [];
  let calls = 0;
  const complete = provider.complete.bind(provider);
  provider.complete = async (request) => {
    calls++;
    if (!MockPass2Provider.isPass2Request(request)) {
      const lastUser = [...request.messages].reverse().find((message) => message.role === 'user');
      if (lastUser) pass1Prompts.push(String(lastUser.content));
    }
    return complete(request);
  };
  return { pass1Prompts, callCount: () => calls };
}

async function seedAcceptedBase(execution: MemoryExecutionRepository): Promise<void> {
  await execution.compareAndSwapAcceptedScene({
    projectId: PROJECT_ID,
    eventId: 'E1',
    expectedVersion: null,
    value: {
      version: 1,
      projectId: PROJECT_ID,
      eventId: 'E1',
      sourceHash: hash('source'),
      revisionId: 'rev-base-1',
      prose: BASE_PROSE,
      proseHash: hash(BASE_PROSE),
      sceneHash: hash(BASE_PROSE),
    },
  });
}

async function seedOpenReview(execution: MemoryExecutionRepository): Promise<string> {
  const manager = new ReviewManager(execution, PROJECT_ID);
  const review = await manager.addReviewComment(
    {
      target: { type: 'scene', id: 'E1' },
      severity: 'suggestion',
      category: 'style',
      content: 'Tighten the opening paragraph.',
    },
    'reviewer',
  );
  return review.id;
}

describe('editorial revision render — resolved accepted bases in Pass 1', () => {
  it('revision request drives base prose + instruction + review material into the provider Pass-1 prompt in deterministic order', async () => {
    const execution = new MemoryExecutionRepository();
    await seedAcceptedBase(execution);
    const reviewId = await seedOpenReview(execution);
    const provider = new MockPass2Provider({ entries: { E1: entry('E1', REVISED_PROSE) } });
    const captured = capture(provider);
    const runtime: EditorialRuntime = {
      provider,
      services: { ...services(provider), execution },
    };

    const result = await renderNovel(
      {
        version: 1,
        source: source(),
        selector: { type: 'events', eventIds: ['E1'] },
        revision: { reviewIds: [reviewId], instruction: 'Rewrite in a colder register.' },
        mutation: { operationId: crypto.randomUUID(), actorId: 'test' },
        model: 'mock-pass2',
      },
      runtime,
    );

    expect(result.errors).toHaveLength(0);
    expect(result.editorialErrors).toHaveLength(0);
    expect(result.results).toHaveLength(1);
    expect(result.results[0]?.released).toBe(true);
    expect(result.results[0]?.cacheHit).toBe(false);
    expect(result.results[0]?.revisionId).not.toBeNull();

    // Actual Pass-1 request content — not plan hashes.
    expect(captured.pass1Prompts).toHaveLength(1);
    const userPrompt = captured.pass1Prompts[0];
    if (userPrompt === undefined) {
      throw new Error('expected a captured Pass-1 user prompt');
    }
    expect(userPrompt).toContain('Previous Accepted Prose (Non-authoritative)');
    expect(userPrompt).toContain(BASE_PROSE);
    expect(userPrompt).toContain('Editorial Revision Instructions');
    expect(userPrompt).toContain('Rewrite in a colder register.');
    expect(userPrompt).toContain(`[${reviewId}] Tighten the opening paragraph.`);
    expect(userPrompt.indexOf('Previous Accepted Prose')).toBeLessThan(
      userPrompt.indexOf('Editorial Revision Instructions'),
    );

    // The promoted revision is parented on the resolved accepted base.
    const promoted = result.results[0]?.revisionId;
    if (promoted === undefined || promoted === null) {
      throw new Error('expected a promoted revision ID');
    }
    const record = await execution.readSceneRevision({
      projectId: PROJECT_ID,
      eventId: 'E1',
      revisionId: promoted,
    });
    expect(record).not.toBeNull();
    expect(record?.value.parentRevisionId).toBe('rev-base-1');
    const accepted = await execution.readAcceptedScene({ projectId: PROJECT_ID, eventId: 'E1' });
    expect(accepted?.value.revisionId).toBe(promoted);
    expect(accepted?.value.proseHash).toBe(hash(REVISED_PROSE));
  });

  it('blocks before any provider call when a revised scene has no accepted base', async () => {
    const execution = new MemoryExecutionRepository();
    const provider = new MockPass2Provider({ entries: { E1: entry('E1', REVISED_PROSE) } });
    const captured = capture(provider);
    const runtime: EditorialRuntime = {
      provider,
      services: { ...services(provider), execution },
    };

    const result = await renderNovel(
      {
        version: 1,
        source: source(),
        selector: { type: 'events', eventIds: ['E1'] },
        revision: { instruction: 'Rewrite in a colder register.' },
        mutation: { operationId: crypto.randomUUID(), actorId: 'test' },
        model: 'mock-pass2',
      },
      runtime,
    );

    expect(captured.callCount()).toBe(0);
    expect(captured.pass1Prompts).toHaveLength(0);
    expect(result.results).toHaveLength(0);
    expect(result.editorialErrors).toHaveLength(1);
    expect(result.editorialErrors[0]?.code).toBe('NO_ACCEPTED_BASE');
    expect(result.editorialErrors[0]?.eventId).toBe('E1');
    expect(result.errors[0]).toContain('E1');
    // The rejected revision never touched the accepted head or the ledger.
    expect(await execution.readAcceptedScene({ projectId: PROJECT_ID, eventId: 'E1' })).toBeNull();
  });

  it('preview represents revision prompts consistently without provider calls', async () => {
    const execution = new MemoryExecutionRepository();
    await seedAcceptedBase(execution);
    const reviewId = await seedOpenReview(execution);
    const provider = new MockPass2Provider({ entries: { E1: entry('E1', REVISED_PROSE) } });
    const captured = capture(provider);
    const runtime: EditorialRuntime = {
      provider,
      services: { ...services(provider), execution },
    };

    const preview = await previewEditorialRun(
      {
        version: 1,
        source: source(),
        selector: { type: 'events', eventIds: ['E1'] },
        revision: { reviewIds: [reviewId], instruction: 'Rewrite in a colder register.' },
        model: 'mock-pass2',
      },
      runtime,
    );

    expect(preview.errors).toHaveLength(0);
    expect(preview.prompts).toHaveLength(1);
    const userPrompt = preview.prompts[0]?.userPrompt;
    expect(userPrompt).toContain('Previous Accepted Prose (Non-authoritative)');
    expect(userPrompt).toContain(BASE_PROSE);
    expect(userPrompt).toContain('Editorial Revision Instructions');
    expect(userPrompt).toContain('Rewrite in a colder register.');
    expect(userPrompt).toContain(`[${reviewId}] Tighten the opening paragraph.`);
    expect(captured.callCount()).toBe(0);
  });

  it('preview reports NO_ACCEPTED_BASE with empty prompts when the base is missing', async () => {
    const execution = new MemoryExecutionRepository();
    const provider = new MockPass2Provider({ entries: { E1: entry('E1', REVISED_PROSE) } });
    const captured = capture(provider);
    const runtime: EditorialRuntime = {
      provider,
      services: { ...services(provider), execution },
    };

    const preview = await previewEditorialRun(
      {
        version: 1,
        source: source(),
        selector: { type: 'events', eventIds: ['E1'] },
        revision: { instruction: 'Rewrite in a colder register.' },
        model: 'mock-pass2',
      },
      runtime,
    );

    expect(preview.prompts).toHaveLength(0);
    expect(preview.editorialErrors[0]?.code).toBe('NO_ACCEPTED_BASE');
    expect(preview.errors[0]).toContain('E1');
    expect(captured.callCount()).toBe(0);
  });

  it('custom prompt catalog templates shape both Pass 1 and preview prompts', async () => {
    const execution = new MemoryExecutionRepository();
    await seedAcceptedBase(execution);
    const reviewId = await seedOpenReview(execution);
    const provider = new MockPass2Provider({ entries: { E1: entry('E1', REVISED_PROSE) } });
    const captured = capture(provider);
    const catalog = {
      get: async (input: { readonly name: string }) =>
        input.name === 'pass1'
          ? {
              name: 'pass1',
              version: '1',
              template: '## Instructions\nWrite exactly in the custom house style.\n',
            }
          : null,
    };
    const runtime: EditorialRuntime = {
      provider,
      services: { ...services(provider, catalog), execution },
    };

    const result = await renderNovel(
      {
        version: 1,
        source: source(),
        selector: { type: 'events', eventIds: ['E1'] },
        revision: { reviewIds: [reviewId], instruction: 'Rewrite in a colder register.' },
        mutation: { operationId: crypto.randomUUID(), actorId: 'test' },
        model: 'mock-pass2',
      },
      runtime,
    );
    expect(result.errors).toHaveLength(0);
    expect(captured.pass1Prompts).toHaveLength(1);
    expect(captured.pass1Prompts[0]).toContain('Write exactly in the custom house style.');
    expect(captured.pass1Prompts[0]).toContain('## Instructions');

    const preview = await previewEditorialRun(
      {
        version: 1,
        source: source(),
        selector: { type: 'events', eventIds: ['E1'] },
        revision: { reviewIds: [reviewId], instruction: 'Rewrite in a colder register.' },
        model: 'mock-pass2',
      },
      runtime,
    );
    expect(preview.errors).toHaveLength(0);
    expect(preview.prompts[0]?.userPrompt).toContain('Write exactly in the custom house style.');
    expect(preview.prompts[0]?.userPrompt).toContain('## Instructions');
  });

  it('fixed injected ids/clock make revision IDs and timestamps deterministic', async () => {
    const FIXED_NOW = '2026-04-05T06:07:08.000Z';
    const run = async () => {
      const execution = new MemoryExecutionRepository();
      await seedAcceptedBase(execution);
      const reviewId = await seedOpenReview(execution);
      const provider = new MockPass2Provider({ entries: { E1: entry('E1', REVISED_PROSE) } });
      const runtime: EditorialRuntime = {
        provider,
        services: {
          ...services(provider),
          execution,
          clock: { now: () => FIXED_NOW },
          ids: { next: () => 'deterministic-rev-1' },
        },
      };
      const result = await renderNovel(
        {
          version: 1,
          source: source(),
          selector: { type: 'events', eventIds: ['E1'] },
          revision: { reviewIds: [reviewId], instruction: 'Rewrite in a colder register.' },
          mutation: { operationId: '33333333-3333-4333-8333-333333333333', actorId: 'test' },
          model: 'mock-pass2',
        },
        runtime,
      );
      return { result, execution };
    };
    const a = await run();
    const b = await run();
    expect(a.result.errors).toHaveLength(0);
    expect(b.result.errors).toHaveLength(0);
    expect(a.result.results[0]?.revisionId).toBe('deterministic-rev-1');
    expect(b.result.results[0]?.revisionId).toBe('deterministic-rev-1');

    // The persisted revision record is byte-identical across runs: same
    // revisionId, same injected createdAt, same parent/base.
    const recA = await a.execution.readSceneRevision({
      projectId: PROJECT_ID,
      eventId: 'E1',
      revisionId: 'deterministic-rev-1',
    });
    const recB = await b.execution.readSceneRevision({
      projectId: PROJECT_ID,
      eventId: 'E1',
      revisionId: 'deterministic-rev-1',
    });
    expect(recA).not.toBeNull();
    expect(recA?.value).toEqual(recB?.value);
    const envelope = recA?.value.value;
    if (typeof envelope === 'object' && envelope !== null && 'createdAt' in envelope) {
      expect(envelope.createdAt).toBe(FIXED_NOW);
    }

    const accepted = await a.execution.readAcceptedScene({ projectId: PROJECT_ID, eventId: 'E1' });
    expect(accepted?.value.revisionId).toBe('deterministic-rev-1');
  });
});
