/**
 * Browser-safe contract surface. Client code may depend on this barrel only.
 * It exports pure data DTOs (projection, presence, capability, session
 * state) — never host handles. Host-internal wire plumbing (persistence
 * operation maps, password hash records), host-only provider credential
 * stores (the OS credential adapter and its XDG file fallback), and the
 * shared ProjectSession/Core runtime implementation are intentionally NOT
 * re-exported here; no filesystem, Git, provider, or database handle ever
 * crosses this boundary.
 */

export type {
  PresenceUpdateV1,
  ProjectPresenceV1,
  ProjectSessionProjectionV1,
  ProjectSourceDiagnosticV1,
  SessionPresenceSurfaceV1,
} from '@novalistically/workbench-protocol';
export type {
  AgentChatAssistantTextEventV1,
  AgentChatCancelResultV1,
  AgentChatContractVersion,
  AgentChatConversationListResultV1,
  AgentChatConversationViewV1,
  AgentChatCreateConversationRequestV1,
  AgentChatCreateConversationResultV1,
  AgentChatHistoryV1,
  AgentChatMessageViewV1,
  AgentChatProgressEventV1,
  AgentChatRunHistoryEntryV1,
  AgentChatRunStatusEventV1,
  AgentChatRunViewV1,
  AgentChatSendMessageRequestV1,
  AgentChatSendMessageResultV1,
  AgentChatToolCallEventV1,
  AgentChatToolCallReceiptV1,
  AgentChatToolResultEventV1,
} from './agent-chat.js';
export type {
  AuthoringActivityEventV1,
  AuthoringConflictKindV1,
  AuthoringConflictV1,
  AuthoringContractVersion,
  AuthoringDiagnosticV1,
  AuthoringDocumentDigestV1,
  AuthoringExternalCandidateV1,
  AuthoringFailureCodeV1,
  AuthoringFailureV1,
  AuthoringNextWorkingActionV1,
  AuthoringOperationKindV1,
  AuthoringOperationReceiptV1,
  AuthoringOperationStatusV1,
  AuthoringPhaseV1,
  AuthoringPresenceMemberV1,
  AuthoringReconcileChoiceV1,
  AuthoringStateV1,
  AuthoringSubmitBlockReasonV1,
  AuthoringSubmitReceiptV1,
  AuthoringWorkspaceDigestV1,
  BrowserAuthoringDocumentCreateRequestV1,
  BrowserAuthoringDocumentDeleteRequestV1,
  BrowserAuthoringDocumentMoveRequestV1,
  BrowserAuthoringDocumentMutationResultV1,
  BrowserAuthoringReconcileRequestV1,
  BrowserAuthoringReconcileResultV1,
  BrowserAuthoringRevisionChangeV1,
  BrowserAuthoringRevisionDiffV1,
  BrowserAuthoringRevisionListV1,
  BrowserAuthoringRevisionRestoreRequestV1,
  BrowserAuthoringRevisionRestoreResultV1,
  BrowserAuthoringRevisionV1,
  BrowserAuthoringSubmitRequestV1,
  BrowserAuthoringSubmitResultV1,
  McpAuthoringApplyInputV1,
  McpAuthoringApplyOutputV1,
  McpAuthoringDocumentGetInputV1,
  McpAuthoringDocumentGetOutputV1,
  McpAuthoringStatusInputV1,
  McpAuthoringStatusOutputV1,
  McpAuthoringSubmitInputV1,
  McpAuthoringSubmitOutputV1,
  McpConflictResolveInputV1,
  McpConflictResolveOutputV1,
  McpOperationGetInputV1,
  McpOperationGetOutputV1,
  WorkingValidationEventResultV1,
  WorkingValidationIssSnapshotV1,
  WorkingValidationIssueV1,
  WorkingValidationResultV1,
} from './authoring.js';
export type {
  BrowserApiErrorCode,
  BrowserApiErrorV1,
  BrowserApiVersion,
  BrowserGraphRouteSelectorV1,
  BrowserProjectActivityV1,
  BrowserProjectCapabilitiesV1,
  BrowserProjectListV1,
  BrowserProjectOverviewV1,
  BrowserProjectReferenceListQueryV1,
  BrowserProjectReferenceListV1,
  BrowserProjectSummaryV1,
  BrowserPublicationGetResultV1,
  BrowserPublicationKindV1,
  BrowserPublicationListV1,
  BrowserPublicationReadQueryV1,
  BrowserPublicationReadResultV1,
  BrowserPublicationRecordV1,
  BrowserPublicationStaleReasonV1,
  BrowserPublicationStatusV1,
  BrowserPublishRequestV1,
  BrowserPublishResultV1,
  BrowserReviewAddRequestV1,
  BrowserReviewApplicationV1,
  BrowserReviewCategoryV1,
  BrowserReviewCommentResultV1,
  BrowserReviewCommentV1,
  BrowserReviewGateDecideRequestV1,
  BrowserReviewGateDecisionResultV1,
  BrowserReviewGateDecisionV1,
  BrowserReviewGateListV1,
  BrowserReviewGateStatusV1,
  BrowserReviewGateV1,
  BrowserReviewHistoryEntryV1,
  BrowserReviewHistoryKindV1,
  BrowserReviewHistoryV1,
  BrowserReviewListV1,
  BrowserReviewSeverityV1,
  BrowserReviewStatusV1,
  BrowserReviewTargetTypeV1,
  BrowserReviewUpdateActionV1,
  BrowserReviewUpdateRequestV1,
  BrowserSessionPrincipalV1,
  ProjectAccessRole,
  WorkbenchProjectFeatureV1,
} from './browser-api.js';
export type {
  AdminDevicePairRequestV1,
  AdminInviteCreateRequestV1,
  AdminNetworkUpdateRequestV1,
  AdminProviderUpdateRequestV1,
  ConfigOperationDiagnosticV1,
  ConfigOperationReceiptV1,
  ConfigOperationStatusV1,
  WorkbenchAdminErrorCode,
  WorkbenchAdminOverviewV1,
  WorkbenchConfigErrorCode,
  WorkbenchConfigurationVersion,
  WorkbenchDeviceSafeViewV1,
  WorkbenchInviteSafeViewV1,
  WorkbenchNetworkReadViewV1,
  WorkbenchProjectSafeViewV1,
  WorkbenchProjectValidationV1,
  WorkbenchProviderReadViewV1,
  WorkbenchSetupErrorCode,
  WorkbenchSetupPhaseV1,
  WorkbenchSetupStatusV1,
} from './configuration.js';
export type {
  WorkbenchBranchDecisionV1,
  WorkbenchBranchPathV1,
  WorkbenchBranchScopeV1,
  WorkbenchBranchSetV1,
  WorkbenchConditionV1,
  WorkbenchDiscourseCoordinateV1,
  WorkbenchGraphBoundaryReferenceV1,
  WorkbenchGraphCoordinateV1,
  WorkbenchGraphDomainV1,
  WorkbenchGraphEdgeClassV1,
  WorkbenchGraphEdgeV1,
  WorkbenchGraphNarrativeEllipsisV1,
  WorkbenchGraphNodeOriginV1,
  WorkbenchGraphNodeV1,
  WorkbenchGraphOutputV1,
  WorkbenchGraphProjectionV1,
  WorkbenchGraphReadV1,
  WorkbenchGraphResolutionV1,
  WorkbenchGraphViewV1,
  WorkbenchGraphViewVersion,
  WorkbenchOutputValueV1,
  WorkbenchPresencePredicateV1,
  WorkbenchReadOriginV1,
  WorkbenchReadPhaseV1,
  WorkbenchRouteChoiceV1,
  WorkbenchRouteEventScopeV1,
  WorkbenchRouteSelectorV1,
  WorkbenchRouteViewV1,
  WorkbenchSceneSequenceEntryV1,
  WorkbenchSceneStoryCoordinateV1,
  WorkbenchStoryCoordinateV1,
} from './graph.js';
export type {
  AuditRecord,
  AuditSurface,
  AuthBackoffState,
  BinaryPayload,
  CapabilityState,
  ConsumeInviteResult,
  DeviceVerifierReadState,
  GitSubmissionJournal,
  GitSubmissionReceipt,
  InviteState,
  OperationCheckpoint,
  SessionState,
  UiPreferences,
  UserRole,
  UserState,
  WorkingDocumentState,
  YjsDocumentKey,
} from './persistence.js';
export type { SceneAdoptionViewV1 } from './scene.js';
export type {
  SourceStudioDocumentDescriptorV1,
  SourceStudioStateV1,
  SourceStudioWorkingDocumentView,
  SourceStudioWorkingLayerV1,
} from './source-studio.js';
